### ISSUE TITLE
Hi, thank you for this software

### ISSUE THREAD

**Issue by clabnet** [otadrive/OTAdriveESP#1]
It's a little magic piece of code, and simply it running now.
I have all configured, and the new firmware version is downloaded correctly when it is found.

How to avoid this error messages : 
```
[E][WiFiClient.cpp:288] setSocketOption(): 1006 : 9
[E][otadrive_esp.cpp:77] head(): downloaded error 304,
```
when there are not a newer version ? 

Thanks a lot, again. 
Regards

**Comment by otadrive** [comment]
Please use the last version of library +1.0.7
