### ISSUE TITLE
Serial number strange ID

### ISSUE THREAD

**Issue by clabnet** [otadrive/OTAdriveESP#2]
The MAC address of my device is `f0:08:d1:c8:fb:ac`

Why the serial number of the same device was identified as : `acfbc8d108f0` ?
It is reverted from right to left. Is not simply remove the `:` and maintain the same MAC address ?

Can be used a custom code to identify the serial device ? 

I normally use this code to extract only the latest 6 chars from the mac address : 
```
uint32_t ESP32_getChipId() {
    uint32_t chipId = 0;
    for (int i = 0; i < 17; i = i + 8) {
        chipId |= ((ESP.getEfuseMac() >> (40 - i)) & 0xff) << i;
    }
    // Serial.print("ESP32_getChipId: ");
    // Serial.println(chipId);
    return chipId;
}
```

Thank,s regards

**Comment by otadrive** [comment]
You can't store 6 bytes of serial numbers into an int32 (4 bytes) variable.
